### ISSUE TITLE
Create PPPoE Connection in Ubuntu 16.04

### ISSUE THREAD

**Issue by cinnamoner** [cinnamoner/The-Mystery-of-PPPoE#1]

**Comment by cinnamoner** [comment]
1. Update System
`sudo apt-get update`

2. Install pppoe
`sudo apt-get install pppoe`

3. Install pppoeconf
`sudo apt-get install pppoeconf`

4. Insert DSL cable to the network port of your computer and enter the following command:
`sudo pppoeconf`

5. When asked if you want the "noauth" and "defaultroute" options and to remove "nodetach", choose "Yes"

6. Enter your user name and password provided by your ISP

7. Choose "Yes" to use peer DNS

8. Choose "Yes" in the "Limited MSS Problem" screen

9. When asked if you want to connect at start up, you may want to choose "Yes"

10. Choose "Yes" to start the connection "now" if you so want

11. To disconnect, run `sudo poff`

12. To reconnect, run `sudo pon dsl-provider`

Should you want to check connection status enter `ifconfig`

**Comment by cinnamoner** [comment]
https://www.howtoinstall.co/en/ubuntu/xenial/pppoe
https://www.linuxbabe.com/ubuntu/create-pppoe-connection-ubuntu-16-04

**Comment by cinnamoner** [comment]
https://help.ubuntu.com/community/ADSLPPPoE

**Comment by cinnamoner** [comment]
@MichaelTunnell Now the connection is fast and rock solid. Any iso downloads fast. 100% success rate. 
Sudo can install anything. But Discover says "no network connection". With router the connection was so so and 75% any iso (not only from Neon) download failure rate. The network manager is useless. I can't establish PPPoE. The setup "as is now" is probably not perfect but the solution is in those links. I have fiber with PPPoE. Have no idea. Windows works. In Linux I have this issues. Any suggestion appreciated.

**Comment by cinnamoner** [comment]
So these two: pppoe and pppoeconf exist as .deb packages. So, say, If I install them off-line, right after installing neon, will it work? The connection is now amazing but surely it's a rough setup. Discover is dead (it populates but can't install anything therefrom as I could before. But sudo apt-get installs everything. But from where? Haven't messed with the sources.

**Comment by cinnamoner** [comment]
@ MichaelTunnell Probably, I haven't explained properly. No OS should deny a PPPoE connection. Neon has a network manager with the DSL PPPoE option. Tried to use it. For whatever reason it didn't work out. My best guess the problem is on Ubuntu's side.
***
Tried PPoE in the router. The router has that option. But it was a failure. Not a complete failure but the resolution is so so and 9 out of 10 iso downloads just fail.
***
This is my connection: broadband fiber with PPPoE that requires user name and password.
***
I'll do further research.
***
@Lestcape Noticed you've stared the repo. Thanks. I'm probably on the right track.

**Comment by cinnamoner** [comment]
Yet another useful link https://askubuntu.com/questions/762372/dsl-connection-setup-in-ubuntu-16-04

**Comment by cinnamoner** [comment]
To do:
1. Reinstall Neon and run `dpkg -s pppoe` and `dpkg -s pppoeconf` to find out if they are included by default or not.
2. If not, find which way to go:
a) offline installing them
b) sudo apt-get installing them (requires some internet connectivity)

**Comment by cinnamoner** [comment]
https://launchpad.net/ubuntu/xenial/+package/pppoe
https://launchpad.net/ubuntu/xenial/+package/pppoeconf

**Comment by cinnamoner** [comment]
I new I would have to deal with this sooner or later. In 14.04 it worked out of the box. In 16.04 it doesn't. Some guidance would be appreciated.

**Comment by cinnamoner** [comment]
@MichaelTunnell Might wonder why further messing with it if the internet already works (as I've set it up).
Because Discover broke in the process. It populates and it shows up the updates but can't fetch anything with it.

I've just used `sudo apt-get update` then `sudo apt-get upgrade` and it worked flawlessly though.

I'm not sure what `sudo apt-get dist-upgrade` and `sudo apt-get autoremove` do.

Have a laugh, then illuminate me. Coming from Windows, you know. I think Discover is for Windows guys. One never knows what's under the hood, whilst in the terminal one can see what actually happens.

**Comment by cinnamoner** [comment]
Let's go to Neon an download an image.

**Comment by cinnamoner** [comment]
Random Neon image download completed without issues in 4 minutes. So now it works and never 99.(9)%  fails. And DNS resolution is very, very good. No hesitations.

**Comment by cinnamoner** [comment]
Yet another thing: I'm not sure if my credentials (given to me by my ISP) are securely stored on the system. Like encrypted or something. The network manager should do that part, but I've circumvented it, or not?

**Comment by cinnamoner** [comment]
`dpkg -s k3b
Package: k3b
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 2104
Maintainer: Kubuntu Developers <kubuntu-devel@lists.ubuntu.com>
Architecture: amd64
Version: 2.0.3-0ubuntu5
Replaces: k3b-data (<< 1.66.0~alpha2-1)
Depends: kde-runtime (>> 4:4.10), libc6 (>= 2.14), libk3b6 (= 2.0.3-0ubuntu5), libkcddb4 (>= 4:4.3.4), libkcmutils4 (>= 4:4.4.95), libkde3support4 (>= 4:4.4.4), libkdecore5 (>= 4:4.4.95), libkdeui5 (>= 4:4.5.85), libkfile4 (>= 4:4.7.0), libkio5 (>= 4:4.4.4), libknotifyconfig4 (>= 4:4.4.4), libqt4-dbus (>= 4:4.5.3), libqt4-qt3support (>= 4:4.5.3), libqt4-xml (>= 4:4.5.3), libqtcore4 (>= 4:4.8.0), libqtgui4 (>= 4:4.8.0), libqtwebkit4, libsolid4 (>= 4:4.4.4), libstdc++6 (>= 4.1.1), k3b-data (= 2.0.3-0ubuntu5), wodim | cdrskin, cdparanoia, cdrdao, genisoimage, udisks2
Recommends: dvd+rw-tools, vcdimager, growisofs, libk3b6-extracodecs
Suggests: k3b-extrathemes, k3b-i18n, normalize-audio, sox, movixmaker-2, kde-config-cddb
Description: Sophisticated CD/DVD burning application
 K3b provides a comfortable user interface to perform most CD/DVD burning
 tasks. While the experienced user can take influence in all steps
 of the burning process the beginner may find comfort in the automatic settings
 and the reasonable k3b defaults which allow a quick start.
Homepage: http://www.k3b.org
Original-Maintainer: Debian KDE Extras Team <pkg-kde-extras@lists.alioth.debian.org>`

Installed via sudo. Doesn't seem to be coming from Neon, does it?

**Comment by cinnamoner** [comment]
***

**Comment by cinnamoner** [comment]
Okay, I'm back.
Status report:
1. Reinstalled Neon
2. Updated the system (had to use something so I used the router with the PPPoE settings inside it)
3. Made it to GitHub
4. Let's run `dpkg -s pppoe` and `dpkg -s pppoeconf`

**Comment by cinnamoner** [comment]
Sadly, neither is on the system. There:

dpkg -s pppoe
dpkg-query: package 'pppoe' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
***
dpkg -s pppoeconf
dpkg-query: package 'pppoeconf' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.

**Comment by cinnamoner** [comment]
K3B is on the system though. Installed it from Discover, after updating. There:
`dpkg -s k3b
Package: k3b
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 2104
Maintainer: Kubuntu Developers <kubuntu-devel@lists.ubuntu.com>
Architecture: amd64
Version: 2.0.3-0ubuntu5
Replaces: k3b-data (<< 1.66.0~alpha2-1)
Depends: kde-runtime (>> 4:4.10), libc6 (>= 2.14), libk3b6 (= 2.0.3-0ubuntu5), libkcddb4 (>= 4:4.3.4), libkcmutils4 (>= 4:4.4.95), libkde3support4 (>= 4:4.4.4), libkdecore5 (>= 4:4.4.95), libkdeui5 (>= 4:4.5.85), libkfile4 (>= 4:4.7.0), libkio5 (>= 4:4.4.4), libknotifyconfig4 (>= 4:4.4.4), libqt4-dbus (>= 4:4.5.3), libqt4-qt3support (>= 4:4.5.3), libqt4-xml (>= 4:4.5.3), libqtcore4 (>= 4:4.8.0), libqtgui4 (>= 4:4.8.0), libqtwebkit4, libsolid4 (>= 4:4.4.4), libstdc++6 (>= 4.1.1), k3b-data (= 2.0.3-0ubuntu5), wodim | cdrskin, cdparanoia, cdrdao, genisoimage, udisks2
Recommends: dvd+rw-tools, vcdimager, growisofs, libk3b6-extracodecs
Suggests: k3b-extrathemes, k3b-i18n, normalize-audio, sox, movixmaker-2, kde-config-cddb
Description: Sophisticated CD/DVD burning application
 K3b provides a comfortable user interface to perform most CD/DVD burning
 tasks. While the experienced user can take influence in all steps
 of the burning process the beginner may find comfort in the automatic settings
 and the reasonable k3b defaults which allow a quick start.
Homepage: http://www.k3b.org
Original-Maintainer: Debian KDE Extras Team <pkg-kde-extras@lists.alioth.debian.org>`
Seems consistent with the previous post so I'll assume I probably don't need Discover anyways (although it's a nice piece of software, I've gotta admit. It's rather whimsical too :))

**Comment by cinnamoner** [comment]
5. I'm tinkering about which would be the best way to install the `pppoe` and `ppoeconf` packages. From the .deb files or via `sudo apt-get intall`. Both ways might have advantages and disadvantages. You're clever enough to figure out why.

Tinkering ...

**Comment by cinnamoner** [comment]
https://launchpad.net/ubuntu/xenial/+package/pppoe
https://launchpad.net/ubuntu/xenial/+package/pppoeconf

Wondering whether those are the right links. Installed them via `sudo apt-get install` before, so I'm considering installation from the .deb files. I'll have them on removable media so I can install them right after fresh installs of the OS.

**Comment by cinnamoner** [comment]
@BigDaddyonTech @MichaelTunnell If anybody feels like an expert, it's now the time to jump in. Kinda feel like Hamlet here, you know :)

**Comment by cinnamoner** [comment]
Seems there's no 64bit-compiled binary for pppoeconf. The 32bit-compiled will work too. It's just that I would've liked a 64bit-compiled one.

**Comment by cinnamoner** [comment]
6. Tried to download an ISO and failed. Downloaded the binaries.

**Comment by cinnamoner** [comment]
7. Tried a compromise: installed pppoe only and tried to make things work from the network manager. Did not work.

**Comment by cinnamoner** [comment]
8. Installed both binaries with the following results:
- Can download any ISO with a success ratio of 99.(9)% (downloaded a Neon ISO in 2 minutes)
- DNS resolution works flawlessly
- Can install anything from the terminal
- Discover is dead (don't need it anyways)

**Comment by cinnamoner** [comment]
Conclusions:
- There's no help like self-help.
- GNU with Linux OSs are hit or miss but preferable to Windows.
- I had to do what I had to do to make it work.
- I'll probably link this thread to the KDE forum. The network manager sucks. They should cut off DSL PPPoE if they don't intend to make it usable.
- Hopefully, this thread will help out people who are desperately looking for a fix to their problem. I've been having this issue ever since 16.04 came out.
- I would still like some opinions and suggestions as to how to improve on the issue.
- Last but not least I would like to address a thank you to myself.

**Comment by cinnamoner** [comment]
@lestcape Staring the repo boosted my confidence. So, Thank you my friend!

**Comment by cinnamoner** [comment]
Conclusions 2:

Whether your ethernet controller was manufactured 10, 5 years ago or yesterday, successfully establishing a DSL-PPPoE connection from the network manager will probably not work.

@MichaelTunnell Ain't that right?

**Comment by cinnamoner** [comment]
https://forum.kde.org/viewtopic.php?f=309&t=140025&sid=e83d12e0235ce63329649d0e2847fbfd

**Comment by MichaelTunnell** [comment]
> @MichaelTunnell Ain't that right?

I don't know. I don't bother with PPPoE and never have so I no input to this topic.

I seriously doubt most businesses care about PPPoE because ethernet is more reliable and faster however with that said, more businesses care about wifi now more so than ethernet.

**Comment by cinnamoner** [comment]
Agreed, but some ISPs use PPPoE.

**Comment by cinnamoner** [comment]
@MichaelTunnell Seems neither of us is an expert in networking. Which is rather unfortunate because networking is an important part of any computing savy person.
***
PPPoE is a protocol and it has nothing to do with speed.
***
There are ISPs using this protocol with state-of-the-art infrastructure. PPPeE was used in the past with networking technologies that are now deprecated. Hence the misconception.
***
The term "ethernet" means nothing in particular, other than a piece of cable.
***
"I don't know" is the accurate answer and the beginning of knowledge.
***
I'll get to the point. If the network manager in KDE Neon has the PPPoE option and it does, then it should be capable to handle the thing.
***

**Comment by cinnamoner** [comment]
@cnddu I need your help.

**Comment by cinnamoner** [comment]
Never set the router to DHCP though. Hmmm.

**Comment by cinnamoner** [comment]
Maybe that damn router is broken. But just in case it ain't, here are the packages for a stable connection in Debian Stable  :)
https://packages.debian.org/jessie/net/pppoeconf

**Comment by cinnamoner** [comment]
This issue drives me nuts.

**Comment by cinnamoner** [comment]
I mean with the router it works decently but any kind of iso download just fails. Whilest with this pppoeconf everything works fine. ISOs download just fine and so forth. The third variant would be the network manager. I have some resolution in the beginning, then it just dies on me. My ISP uses pppoe. And that's that.

**Comment by MichaelTunnell** [comment]
> Which is rather unfortunate because networking is an important part of any computing savy person.

No, it isn't.

--------------

> The term "ethernet" means nothing in particular, other than a piece of cable.

It does have a meaning. It refers to IEEE 802.3 which defines LAN access method using CSMA/CD. Ethernet beat out other LAN techs like FDDI and ARCNET.

Essentially a specific type of wired connection . . . just because it became the dominant one doesn't mean it was the only one or that "it's just a cable".

--------

> If the network manager in KDE Neon has the PPPoE option and it does, then it should be capable of handling it.

So your issue directly relates to KDE Neon, then you need to talk to the KDE Neon team. Although, this might not be Neon specifically related as it might be an Ubuntu issue. Either way, posting on a random github issue that no one involved with the project you are wondering about is participating in, seems like a waste of time to me.

**Comment by cinnamoner** [comment]
@MichaelTunnell Thanks. I still think the router is the way to go. Perhaps I've missconfigured somthing. You do use a router, don't you? One can even turn a low power client (ex.a computer) into a router.

**Comment by cinnamoner** [comment]
I think it's package fragmentation.

**Comment by cinnamoner** [comment]
@cnddu Does your software work on 16.04? I need some guidance, please.

**Comment by cinnamoner** [comment]
> So your issue directly relates to KDE Neon, then you need to talk to the KDE Neon team

@MichaelTunnell I'm trying to ping you as little as possible. I understand you're involved in a number of projects and whatnot throughout the Linux community.
***
This PPPoE issue is like a rare disease, that's why it's dismissed entirely. Most would not even have the slightest idea what I'm talking about.
***
I'm satisfied with the solution I've found. _It just works._ The only shortcoming would be that it brakes Discover. (I doesn't brake App Grid though.) I can live without Discover but rather not, especially because it's fused with the update manager. Again, Discover populates but when I wanna fetch something therefrom it says: _No connection detected._ 
***
Yet another thing. I've installed `pppoe` and `pppoeconf` by making use of 3 different methods so far: sudo apt-get install, downloadable binaries and ... one-click-install from ... Discover itself.
***
So you suggest to talk with the Neon team. Alright. Should I contact Jonathan himself? Or what? That KDE forum is so so. Like any forum, I guess.
***
PS: Nope. The router route doesn't work. It might be a faulty router or an obscure setting. It should work in theory but it doesn't in practice. I could probably take a lot of time to figure it out. If it's possible at all.

**Comment by cinnamoner** [comment]
I might be building a Ubuntu-based router. Man, one thing I like about Ubuntu is that there's documentation. But pretty much everything comes from Debian.

**Comment by MichaelTunnell** [comment]
> So you suggest to talk with the Neon team. Alright. Should I contact Jonathan himself? Or what?

I don't know what the best method is for this . . . maybe the IRC channel for Neon, don't know.

What I do know is that posting a gigantic thread on a github issue that no-one involved with the project will ever see is just "shouting into the wind".

**Comment by cinnamoner** [comment]
@MichaelTunnell Issue successfully solved. It was a faulty router. But now I'm considering ipfire. I recall you having had suggested it. Is it the best all-in-one? Anyways, now I'm looking for a thin client with passive cooling but still powerful enough to accommodate it. Yeah, building my own router and more ... It's fun.

**Comment by cinnamoner** [comment]
01cea759f175b7ac8024df3fb9cba53c5665ab69963a04b3eacb2caaf5e3b64d

**Comment by cinnamoner** [comment]
9362520ef285dafbbb51638fc86087eafd78773ec27fe699c05fd19a0e367bc5
